Ajout des pages tech pour ruby et ruby on rails
popcorn-nantes/popcorn-nantes pull request #206
Opened 2020-09-24 07:50 UTC by achorein

Ajout des pages associées aux tech ruby et ror
Image par default popcorn

2020-09-24 07:53 UTC, achorein commented
@agnesmdev est-ce que tu pourrais rajouter l'image de background pour les tech ? que l'on puisse refaire les vignettes pour les nouvelles tech :smile:

2020-09-24 08:02 UTC, agnesmdev commented
Je te fais ça dans l'aprèm 😉

2020-09-25 07:54 UTC, agnesmdev requested changes

2020-09-25 07:54 UTC, agnesmdev commented on content/technologies/ruby-on-rails.md
> +image: /media/images/logo-popcorn-ruby-on-rails.jpg
Tu pourrais changer le nom de l'image pour qu'elle corresponde ? Actuellement, son nom est "logo-popcorn-rubyonrails.png"

2020-09-25 07:54 UTC, agnesmdev commented on content/technologies/ruby-on-rails.md
> +image: /media/images/logo-popcorn-ruby-on-rails.jpg
Et retirer les deux images par défaut aussi :)

2020-09-25 09:32 UTC, achorein commented on content/technologies/ruby-on-rails.md
> +image: /media/images/logo-popcorn-ruby-on-rails.jpg
c'est fait :+1:

2020-09-25 16:28 UTC, merged