Nouveau profil : Julien Belinga
popcorn-nantes/popcorn-nantes pull request #320
Opened 2022-11-19 21:53 UTC by julienBelinga

Bonjour,
J'adore le concept. Merci de m'ajouter dans le communauté.

2022-11-22 06:36 UTC, alvinberthelot requested changes
Salut Julien, quelques petites retouches avant d'être chez nous ;)

2022-11-22 06:36 UTC, alvinberthelot commented on content/persons/julien-belinga.md
> +Je suis un développeur avec près de 2 ans d’expérience, motiver et ayant acquis de l’expérience professionnelle en temps que développeur web, je saurai m’adapter rapidement et me montrer pro-actif.
motiver => motivé

2022-11-22 06:36 UTC, alvinberthelot commented on content/persons/julien-belinga.md
> +photo: julien-belinga.jpg
Ta photo est trop volumineuse, cf. README : Ajoute ta photo dans le dossier /static/media/photos : la photo doit faire 100ko maximum ⚠️.

2022-11-22 13:20 UTC, julienBelinga commented
Merci pour les retours, c'est corriger! :)

2022-11-23 13:06 UTC, alvinberthelot commented
Bienvenue sur Popcorn 🍿! Tu vas recevoir une invitation sur notre tchat privé, c'est là que nous échangeons les plans tafs sur notre canal #tuyaux-boulots et que nous papotons autour du freelancing et du dev sur #general. Ton profil sera visible sur le site d'ici quelques minutes. A bientôt

2022-11-23 13:06 UTC, merged