Nouveau profil : Aleth
popcorn-nantes/popcorn-nantes pull request #330
Opened 2023-02-06 14:51 UTC by planeth44

2023-02-08 09:19 UTC, alvinberthelot requested changes

2023-02-08 09:19 UTC, alvinberthelot commented on content/persons/aleth-gueguen.md
> +photo: placeholder-5.png
Le nom fichier ne correspond pas à ce que tu as mis dans static/media/photos

2023-02-20 09:43 UTC, planeth44 commented on content/persons/aleth-gueguen.md
> +photo: placeholder-5.png
J'ai fait la correction

2023-02-21 19:11 UTC, alvinberthelot commented
Bienvenue sur Popcorn 🍿! Tu vas recevoir une invitation sur notre tchat privé, c'est là que nous échangeons les plans tafs sur notre canal #tuyaux-boulots et que nous papotons autour du freelancing et du dev sur #general. Ton profil sera visible sur le site d'ici quelques minutes. A bientôt !

2023-02-21 19:11 UTC, merged