Nouveau profil : Erwan Jestin
popcorn-nantes/popcorn-nantes pull request #370
Opened 2024-05-20 09:49 UTC by ErwanJes

2024-05-20 14:27 UTC, alvinberthelot requested changes

2024-05-20 14:27 UTC, alvinberthelot commented on content/persons/_erwan-jestin.md
> +---
Ton fichier est préfixé par un "underscore", ton profil ne sera donc pas pris en considération

2024-05-21 19:24 UTC, ErwanJes commented on content/persons/_erwan-jestin.md
> +---
Bien vu !

2024-05-24 06:32 UTC, alvinberthelot commented
Bienvenue sur Popcorn 🍿! Tu vas recevoir une invitation sur notre tchat privé, c'est là que nous échangeons les plans tafs sur notre canal #tuyaux-boulots et que nous papotons autour du freelancing et du dev sur #general. Ton profil sera visible sur le site d'ici quelques minutes. A bientôt !

2024-05-24 06:32 UTC, merged